name: se7a_we_3afia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  intl: ^0.20.0
  json_serializable: ^6.8.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
